//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace auctionSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BidTable
    {
        public int BidId { get; set; }
        public string BidderName { get; set; }
        public string BidderText { get; set; }
        public Nullable<int> ItemId { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<decimal> Bidprice { get; set; }
        public Nullable<int> BidQuantity { get; set; }
        public Nullable<System.DateTime> close_date { get; set; }
        public Nullable<System.DateTime> BidDate { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> approve_bid { get; set; }
        public string Bid_status { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual User User { get; set; }
    }
}
